### ISSUE TITLE
Unable to Select Multiple Items in `Dropdown()`

### ISSUE THREAD

**Issue by kyle-power** [Appsilon/shiny.fluent#29]
When using `Dropdown()` or `updateDropdown()` with `multiSelect = TRUE`, users are unable to select/click items.

```r
updateDropdown(session = session, input_id = "equipment", 
               label = "Select Desired Equipment", placeholder = "Select an option...",
               options = y, styles = list(root = list(width = "10vw"), 
               dropdownItemsWrapper = list(`max-height` = "400px", overflow = "auto")),
               multiSelect = TRUE, disabled = FALSE)
```

Checkboxes are "greyed out" and not able to clicked
![image](https://user-images.githubusercontent.com/79020902/116590126-04698980-a8e3-11eb-99a1-2b9cde9e6624.png)

**Comment by kyle-power** [comment]
Not sure if I need to tag anyone... @kamilzyla sorry to bother you again

**Comment by kamilzyla** [comment]
Hey @kyle-power! You're not bothering at all - thanks for reporting this and sorry for the late response.

The behavior you described is also present in the newest 0.2.0 release of shiny.fluent and it is due to a limitation in our wrapper implementation. For now, the simplified `Dropdown.shinyInput` doesn't work with `multiselect = TRUE`.

It is possible to use multiselect with the bare React interface, but it will require some gymnastics. You can play with this example to see how it works:
```R
shinyApp(
  ui = fluentPage(
    textOutput("value"),
    Dropdown(
      onChange = setInput("dropdown", 2),
      options = list(
        list(key = "A", text = "Option A"),
        list(key = "B", text = "Option B")
      ),
      multiSelect = TRUE
    ),
  ),
  server = function(input, output) {
    output$value <- renderText(deparse(input$dropdown))
  }
)
```

We should be able to add support for `multiSelect = TRUE` in a future release. I created a feature request for this in #42.
