### ISSUE TITLE
support for `downloadButton()`

### ISSUE THREAD

**Issue by kyle-power** [Appsilon/shiny.fluent#39]
Workaround for PrimaryButton() as a download button

**Comment by kamilzyla** [comment]
Thanks @kyle-power for your question, and @jakubsob for a workaround! Starting downloads from React is a feature that we could add to shiny.react in a future release - I created issue Appsilon/shiny.react#11 to track it.

**Comment by jhk0530** [comment]
Hi, all. 
I tried to solve my download button problem using workaround given by @jakubsob .

But in my code, download button will open new page instead of download file. 

so I deleted almost every code to find what's problem, and found this.

When download button is exist in **`Stack`** it won't work properly (instead it will open new page)

So In my case, I replaced `Stack` to `div` and it worked. 

Below is minimal reproducible example. 

I'm even not sure what's different between `div` and `Stack` but, you may want to note.

Thanks.  

--- 
``` r
library(shiny)
library(shiny.fluent)
#> 
#> Attaching package: 'shiny.fluent'
#> The following object is masked from 'package:shiny':
#> 
#>     runExample
library(shinyjs)
#> 
#> Attaching package: 'shinyjs'
#> The following object is masked from 'package:shiny.fluent':
#> 
#>     runExample
#> The following object is masked from 'package:shiny':
#> 
#>     runExample
#> The following objects are masked from 'package:methods':
#> 
#>     removeClass, show

ui <- fluentPage(
  useShinyjs(),
  PrimaryButton.shinyInput(
    "downloadButton",
    text = "Download",
    iconProps = list(iconName = "Download")
  ),
  Stack(
    style = "visibility: hidden;",
    downloadButton("download", label = "")
  )
)

server <- function(input, output, session) {
  observeEvent(input$downloadButton, {
    click("download")
  })
  
  output$download <- downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(iris, file)
    }
  )
}

shinyApp(ui, server)
#> 
#> Listening on http://127.0.0.1:3765
```

<sup>Created on 2023-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
